# -*- coding: utf-8 -*-
"""C2L7-Classwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssHgs0P-HzcWZkI_a4HIbPUrPDGAZtnd
"""

import pandas as pd
df =  pd.read_csv('/content/RFM_Retail.csv', encoding = 'latin-1')

df

df.info()

df.describe()

RFM = df.groupby('Customer ID').agg(order_frequency = ('Order ID', 'nunique'), order_money = ('Sales', 'sum')).reset_index()
RFM

df['Order Date'] = pd.to_datetime(df['Order Date'])

Recency = df[['Customer ID', 'Order Date']]

#Assume that the report is conducted on 01/01/2018
Recency['order_recency'] = (pd.to_datetime('01/01/2018') - pd.to_datetime(df['Order Date'])).dt.days

R_score = Recency.groupby('Customer ID').min('order_recency')

R_score

RFM = pd.merge(RFM, R_score, on ='Customer ID', how = 'inner')[['Customer ID', 'order_frequency', 'order_money', 'order_recency']]
RFM

RFM.describe()

RFM['R_Score'] = pd.qcut(RFM['order_recency'] , [0,0.2,0.4,0.6,0.8,1] , labels = [4,3,2,1,0 ])
RFM['F_Score'] = pd.qcut(RFM['order_frequency'] , [0,0.2,0.4,0.6,0.8,1] , labels = [0,1,2,3,4 ])
RFM['M_Score'] = pd.qcut(RFM['order_money'] , [0,0.2,0.4,0.6,0.8,1] , labels = [0,1,2,3,4 ])
RFM

RFM['RFM_Score'] = RFM['R_Score'].astype(str) + RFM['F_Score'].astype(str) + RFM['M_Score'].astype(str)

# Define the segment based on RFM scores
data = {
    'Segment': ['VIP Champions', 'Loyal', 'Potential Loyalist', 'Promising', 'New Customers',
                'Need Attention', 'About To Sleep', 'At Risk', 'Cannot Lose Them',
                'Hibernating customers', 'Lost customers'],
    'Scores': [['444', '443', '433', '434', '343', '344', '334'],
               ['432', '333', '324', '244', '243', '234', '233', '224'],
               ['442', '440', '441', '430', '431', '422', '421', '420', '341', '340', '331', '330', '320',
                '342', '322', '321', '312', '242', '241', '240', '231', '230', '222', '212'],
               ['414', '413', '412', '411', '410', '404', '403', '402', '314', '313', '302', '303', '304',
                '204', '203', '202'],
               ['401', '400', '311', '310', '301', '300', '200'],
               ['424', '423', '332', '323', '232', '223', '214', '213'],
               ['220', '210', '201', '110', '102', '120', '130', '140'],
               ['144', '143', '134', '133', '142', '141', '132', '131', '124', '123', '114', '113', '042',
                '041', '034', '032', '031', '024', '023', '022', '014', '013'],
               ['044', '043', '033', '103', '104', '004', '003', '002'],
               ['221', '211', '122', '121', '112', '111', '021', '012', '011', '101', '100'],
               ['000', '001', '010', '020', '030', '040']]
}
data


df_segment = pd.DataFrame(data)

df_segment = df_segment.explode('Scores')

df_segment

RFM_final = pd.merge(RFM, df_segment, how = 'left', left_on = 'RFM_Score', right_on = 'Scores')

RFM_final['Segment'].value_counts()

import plotly.express as px

px.scatter_3d(RFM_final, 'order_recency', 'order_frequency', 'order_money', color = 'Segment')